# Generated by Django 4.2.16 on 2024-10-14 14:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0002_alter_note_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='note',
            name='updated_at',
            field=models.DateTimeField(default=datetime.datetime(2024, 10, 14, 14, 52, 11, 213865, tzinfo=datetime.timezone.utc)),
        ),
    ]
